{
 "openapi": "3.0.1",
 "info": {
  "title": "Zoho Work Drive Documentation",
  "description": "Work Drive API",
  "license": {
   "name": "Apache 2.0"
  },
  "version": "1.0"
 },
 "servers": [
  {
   "url": "https://sakthi-15300.tsi.zohocorpin.com:8556"
  }
 ],
 "tags": [
  {
   "name": "overview",
   "description": "",
   "type": "text"
  },
  {
   "name": "getting started",
   "description": "",
   "type": "text"
  },
  {
   "name": "OAuth 2.0 Authentication",
   "description": "",
   "type": "text"
  },
  {
   "name": "Files/Folders"
  },
  {
   "name": "File Version"
  },
  {
   "name": "Users"
  },
  {
   "name": "Teams"
  },
  {
   "name": "Team Members"
  },
  {
   "name": "Team Folder"
  },
  {
   "name": "Team Folder Members"
  },
  {
   "name": "Groups"
  },
  {
   "name": "Group Members"
  },
  {
   "name": "Folders"
  },
  {
   "name": "Folder Customization"
  },
  {
   "name": "Get Recent Changes"
  },
  {
   "name": "File/Folder Sharing"
  },
  {
   "name": "Chunk Upload"
  },
  {
   "name": "Search"
  },
  {
   "name": "External Sharing"
  },
  {
   "name": "Comments"
  },
  {
   "name": "Team Member Files"
  },
  {
   "name": "My Folders Files"
  },
  {
   "name": "Collect Files"
  },
  {
   "name": "Follow Updates"
  },
  {
   "name": "Data Templates and Custom Fields"
  },
  {
   "name": "Templates"
  },
  {
   "name": "Labels"
  },
  {
   "name": "aicontent"
  },
  {
   "name": "Data Loss Prevention",
   "description": "Manage Data Loss Prevention Policies"
  },
  {
   "name": "filesummary"
  },
  {
   "name": "Images"
  },
  {
   "name": "Languages"
  },
  {
   "name": "PlatformAIDetail"
  },
  {
   "name": "structuredextraction"
  },
  {
   "name": "texttransformation"
  }
 ],
 "paths": {
  "v1/workdrive/download/{resource_id}#downloadServerFile": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Download File",
    "requestType": "http",
    "operationId": "isDownloadAuthorized_downloadServerFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ,ZohoFiles.files.READ"
      ]
     }
    ],
    "servers": [
     {
      "url": "https://download.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "v1/workdrive/download/{resource_id}#downloadServerFileVersion": {
   "get": {
    "tags": [
     "File Version"
    ],
    "summary": "Download File Version",
    "requestType": "http",
    "operationId": "isDownloadAuthorized_downloadServerFileVersion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ,ZohoFiles.files.READ"
      ]
     }
    ],
    "servers": [
     {
      "url": "https://download.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "downloadprogress#downloadProgress": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Multi Download Progress",
    "requestType": "http",
    "operationId": "download_downloadProgress",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}#getTemplateCategoryInfo": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get Category Info",
    "requestType": "http",
    "operationId": "findOne_getTemplateCategoryInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.READ"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}/files#fetchcategoryfileslist": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get all Templates in a Template Category",
    "requestType": "http",
    "operationId": "findManyTargets_fetchcategoryfileslist",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.READ"
      ]
     }
    ]
   }
  },
  "api/v1/changes#GetListOfRecentChanges": {
   "get": {
    "tags": [
     "Get Recent Changes"
    ],
    "summary": "Get list of Recent Changes",
    "requestType": "http",
    "operationId": "findAll_GetListOfRecentChanges",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/changes/{resource_id}#GetStartToken": {
   "get": {
    "tags": [
     "Get Recent Changes"
    ],
    "summary": "Get Start Token",
    "requestType": "http",
    "operationId": "findOne_GetStartToken",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#GetCollectionInfo": {
   "get": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Get Collection Info",
    "requestType": "http",
    "operationId": "findOne_GetCollectionInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.READ"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}/submissions#GetListOfAllCollectionSubmissions": {
   "get": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Get list of all Submissions",
    "requestType": "http",
    "operationId": "findManyTargets_GetListOfAllCollectionSubmissions",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.READ"
      ]
     }
    ]
   }
  },
  "api/v1/comments/{comment_id}#getCommentInfo": {
   "get": {
    "tags": [
     "Comments"
    ],
    "summary": "Get Comment Info",
    "requestType": "http",
    "operationId": "findOne_getCommentInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.READ"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}/customfields#getListOfCustomFieldsOfDataTemplate": {
   "get": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Get List of Custom Fields",
    "requestType": "http",
    "operationId": "findManyTargets_getListOfCustomFieldsOfDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.READ"
      ]
     }
    ]
   }
  },
  "api/v1/groups/{group_id}/groupmembers#getGroupMembers": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get List of Group Members",
    "requestType": "http",
    "operationId": "findManyTargets_getGroupMembers",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.READ"
      ]
     }
    ]
   }
  },
  "api/v1/groupmembers/{group_member_id}#getGroupMemberInfo": {
   "get": {
    "tags": [
     "Group Members"
    ],
    "summary": "Get Group Member Info",
    "requestType": "http",
    "operationId": "findOne_getGroupMemberInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.READ"
      ]
     }
    ]
   }
  },
  "api/v1/groups/{group_id}#getGroupInfo": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get Group Info",
    "requestType": "http",
    "operationId": "findOne_getGroupInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.READ"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}#getLabel": {
   "get": {
    "tags": [
     "Labels"
    ],
    "summary": "Get Label",
    "requestType": "http",
    "operationId": "findOne_getLabel",
    "security": [
     {
      "Authorization": [
       "WorkDrive.labels.READ"
      ]
     }
    ]
   }
  },
  "api/v1/libraries/{library_id}/categories#fetchLibraryCategoriesList": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get list of Categories",
    "requestType": "http",
    "operationId": "findManyTargets_fetchLibraryCategoriesList",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.READ"
      ]
     }
    ]
   }
  },
  "api/v1/libraries/{library_id}/permissions#fetchLibraryPermissions": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get Template Library Permissions",
    "requestType": "http",
    "operationId": "findManyTargets_fetchLibraryPermissions",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.sharing.READ"
      ]
     }
    ]
   }
  },
  "api/v1/libraries#fetchPublicLibraries": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get Public Templates Library ID",
    "requestType": "http",
    "operationId": "findAll_fetchPublicLibraries",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.READ"
      ]
     }
    ]
   }
  },
  "api/v1/libraries/{library_id}#fetchlibrariesinfo": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get Template Library Info",
    "requestType": "http",
    "operationId": "findOne_fetchlibrariesinfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.READ"
      ]
     }
    ]
   }
  },
  "api/v1/libraries/{library_id}/files#fetchlibraryfileslist": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get all Templates from a Template Library",
    "requestType": "http",
    "operationId": "findManyTargets_fetchlibraryfileslist",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.READ"
      ]
     }
    ]
   }
  },
  "api/v1/links/{link_id}#getLinkInfo": {
   "get": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Get External Share Link Info",
    "requestType": "http",
    "operationId": "findOne_getLinkInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.READ"
      ]
     }
    ]
   }
  },
  "api/v1/members/{member_id}#getCollaborationInfo": {
   "get": {
    "tags": [
     "Team Folder Sharing"
    ],
    "summary": "Get TeamFolder Collaboration Info",
    "requestType": "http",
    "operationId": "findOne_getCollaborationInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.READ"
      ]
     }
    ]
   }
  },
  "api/v1/permissions/{permission_id}#getCollaborationInfo": {
   "get": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Get File/Folder Collaboration Info",
    "requestType": "http",
    "operationId": "findOne_getCollaborationInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.READ"
      ]
     }
    ]
   }
  },
  "api/v1/privatespace/{myfolder_id}/links#myFolderLinks": {
   "get": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Get My Folders Links",
    "requestType": "http",
    "operationId": "findManyTargets_myFolderLinks",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/privatespace/{myfolder_id}/files#myFolderFiles": {
   "get": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Get Files in My Folders",
    "requestType": "http",
    "operationId": "findManyTargets_myFolderFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/privatespace/{myfolder_id}/folders#subFolders": {
   "get": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Get Folders in My Folders",
    "requestType": "http",
    "operationId": "findManyTargets_subFolders",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/privatespace/{myfolder_id}/trashedfiles#myTrashedFiles": {
   "get": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Get Trashed Files in My Folders",
    "requestType": "http",
    "operationId": "findManyTargets_myTrashedFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/comments#getComments": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File Comments",
    "requestType": "http",
    "operationId": "findManyTargets_getComments",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/custommetadata#getListOfDataTemplatesAssociatedWithFileFolder": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get list of associated Data Templates",
    "requestType": "http",
    "operationId": "findManyTargets_getListOfDataTemplatesAssociatedWithFileFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/links#getSharedLinks": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File/Folder External Share Links",
    "requestType": "http",
    "operationId": "findManyTargets_getSharedLinks",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/permissions#getSharedUsers": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get Shared Users of File",
    "requestType": "http",
    "operationId": "findManyTargets_getSharedUsers",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{folder_id}/files#getFileList": {
   "get": {
    "tags": [
     "Folders"
    ],
    "summary": "List Files/Folders inside a Folder",
    "requestType": "http",
    "operationId": "findManyTargets_getFileList",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/versions#getVersion": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File Versions",
    "requestType": "http",
    "operationId": "findManyTargets_getVersion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/breadcrumbs#breadcrumbsOfFile": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File/Folder Breadcrumbs",
    "requestType": "http",
    "operationId": "findManyTargets_breadcrumbsOfFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/previewinfo#getFilePreview": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get Preview Meta Data",
    "requestType": "http",
    "operationId": "findOneTarget_getFilePreview",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#fileInfo": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File/Folder Info",
    "requestType": "http",
    "operationId": "findOne_fileInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#getFileThumbnail": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File Thumbnail URL",
    "requestType": "http",
    "operationId": "findOne_getFileThumbnail",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/resourceproperty/{resource_id}#fileProperty": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File/Folder ResourceProperty",
    "requestType": "http",
    "operationId": "findOneTarget_fileProperty",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/statistics#getFileStatistics": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Get File/Folder statistics",
    "requestType": "http",
    "operationId": "findOneTarget_getFileStatistics",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/settings#getTeamFolderSetting": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Settings",
    "requestType": "http",
    "operationId": "findOne_getTeamFolderSetting",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/settings#getTeamSetting": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Team Settings",
    "requestType": "http",
    "operationId": "findOne_getTeamSetting",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.admin.READ"
      ]
     }
    ]
   }
  },
  "api/v1/submissions/{submission_id}/files#GetListOfAllTheSubmittedFiles": {
   "get": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Get list of all user submissions",
    "requestType": "http",
    "operationId": "findManyTargets_GetListOfAllTheSubmittedFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/collections#GetListOfAllCollectionLinks": {
   "get": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Get list of all Collection links",
    "requestType": "http",
    "operationId": "findManyTargets_GetListOfAllCollectionLinks",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/datatemplates#getListOfDataTemplatesInATeam": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get List of Data Templates in a Team",
    "requestType": "http",
    "operationId": "findManyTargets_getListOfDataTemplatesInATeam",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/files#getTeamFolderFiles": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Files and Folders",
    "requestType": "http",
    "operationId": "findManyTargets_getTeamFolderFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/folders#getTeamFolderFolders": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get list of Sub Folders",
    "requestType": "http",
    "operationId": "findManyTargets_getTeamFolderFolders",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/unreadfiles#getUnreadFiles": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Unread Files",
    "requestType": "http",
    "operationId": "findManyTargets_getUnreadFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/trashedfiles#getTrashedFiles": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Trashed Files",
    "requestType": "http",
    "operationId": "findManyTargets_getTrashedFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.admin.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/mydrafts#getMyDraftFiles": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder MyDraft Files",
    "requestType": "http",
    "operationId": "findManyTargets_getMyDraftFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/links#getTeamFolderLinks": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Links",
    "requestType": "http",
    "operationId": "findManyTargets_getTeamFolderLinks",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.admin.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}/members#getTeamFolderSharedUsers": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Members",
    "requestType": "http",
    "operationId": "findManyTargets_getTeamFolderSharedUsers",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#GetTeamFoldersInfo": {
   "get": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Get Team Folder Info",
    "requestType": "http",
    "operationId": "findOne_GetTeamFoldersInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/groups#listTeamGroups": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Groups in a Team",
    "requestType": "http",
    "operationId": "findManyTargets_listTeamGroups",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/libraries#fetchteamlibraries": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get Org Templates Library ID",
    "requestType": "http",
    "operationId": "findManyTargets_fetchteamlibraries",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}#GetTeamInfo": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Team Info",
    "requestType": "http",
    "operationId": "findOne_GetTeamInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchDataTemplate": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search based on Data Template",
    "requestType": "http",
    "operationId": "findManyTargets_SearchDataTemplate",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchAcrossFolder": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search across Folder",
    "requestType": "http",
    "operationId": "findManyTargets_SearchAcrossFolder",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchSharedWithMe": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search in Shared with Me",
    "requestType": "http",
    "operationId": "findManyTargets_SearchSharedWithMe",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchTeamFiles": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search across Team",
    "requestType": "http",
    "operationId": "findManyTargets_SearchTeamFiles",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchTeamFolder": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search across Team Folder",
    "requestType": "http",
    "operationId": "findManyTargets_SearchTeamFolder",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/records#SearchMyFolders": {
   "get": {
    "tags": [
     "Search"
    ],
    "summary": "Search in My Folders",
    "requestType": "http",
    "operationId": "findManyTargets_SearchMyFolders",
    "security": [
     {
      "Authorization": [
       "ZohoSearch.securesearch.READ,WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/teamfolders#GetAllTeamFolders": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Team Folders in a Team",
    "requestType": "http",
    "operationId": "findManyTargets_GetAllTeamFolders",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/users#getTeamUsers": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Team Members",
    "requestType": "http",
    "operationId": "findManyTargets_getTeamUsers",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/currentuser#getCurrentTeamUser": {
   "get": {
    "tags": [
     "Teams"
    ],
    "summary": "Get Current Team Member",
    "requestType": "http",
    "operationId": "findManyTargets_getCurrentTeamUser",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/privatespace#getMyFolderId": {
   "get": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Get My Folders Id",
    "requestType": "http",
    "operationId": "findManyTargets_getMyFolderId",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/suggestedFiles#suggestedFiles": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Suggested Files",
    "requestType": "http",
    "operationId": "findManyTargets_suggestedFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/incomingfiles#sharedWithMeFiles": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Files in Shared with Me",
    "requestType": "http",
    "operationId": "findManyTargets_sharedWithMeFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/recentfiles#recentFiles": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Recent Files",
    "requestType": "http",
    "operationId": "findManyTargets_recentFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/favoritedfiles#favoriteFiles": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Favorited Files",
    "requestType": "http",
    "operationId": "findManyTargets_favoriteFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/incomingfolders#sharedWithMeFolders": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Folders in Shared with Me",
    "requestType": "http",
    "operationId": "findManyTargets_sharedWithMeFolders",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/labeledfiles#labeledFiles": {
   "get": {
    "tags": [
     "Team Member Files"
    ],
    "summary": "Get Labeled Files",
    "requestType": "http",
    "operationId": "findManyTargets_labeledFiles",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/groups#getUserGroups": {
   "get": {
    "tags": [
     "Team Members"
    ],
    "summary": "Get Team Member's Groups",
    "requestType": "http",
    "operationId": "findManyTargets_getUserGroups",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/labels#getLabels": {
   "get": {
    "tags": [
     "Labels"
    ],
    "summary": "Get All Labels of the User",
    "requestType": "http",
    "operationId": "findManyTargets_getLabels",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/libraries#fetchuserlibraries": {
   "get": {
    "tags": [
     "Templates"
    ],
    "summary": "Get My Templates Library ID",
    "requestType": "http",
    "operationId": "findManyTargets_fetchuserlibraries",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}#getMemberInfo": {
   "get": {
    "tags": [
     "Team Members"
    ],
    "summary": "Get Team Member Info",
    "requestType": "http",
    "operationId": "findOne_getMemberInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/me#getUserInfo#getUserInfo": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get User Info",
    "requestType": "http",
    "operationId": "findOne_getUserInfo",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}/collaborators#getUserCollaborators": {
   "get": {
    "tags": [
     "Team Members"
    ],
    "summary": "Get Team Member Collaborators",
    "requestType": "http",
    "operationId": "findManyTargets_getUserCollaborators",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users/{zuid}/teams#GetAllTeamsOfUser": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get All Teams of User",
    "requestType": "http",
    "operationId": "findManyTargets_GetAllTeamsOfUser",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.READ"
      ]
     }
    ]
   }
  },
  "uploadprogress#uploadStatus": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Upload Progress",
    "requestType": "http",
    "operationId": "doGet_uploadStatus",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "zipprogress#zipProgressFile": {
   "get": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Create ZIP Progress",
    "requestType": "http",
    "operationId": "doGet_zipProgressFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/uploadsession#chunkUploadStatus": {
   "get": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Upload Session Progress",
    "requestType": "http",
    "operationId": "doGet_chunkUploadStatus",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/multizip#multiDownload": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Download Multiple Files/Folders as ZIP",
    "requestType": "http",
    "operationId": "doPost_multiDownload",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/actions#emptyTrash": {
   "post": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Empty Team Folder Trash",
    "requestType": "http",
    "operationId": "save_emptyTrash",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/actions#emptyMyFolderTrash": {
   "post": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Empty My Folders Trash",
    "requestType": "http",
    "operationId": "save_emptyMyFolderTrash",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/category#createTemplateCategory": {
   "post": {
    "tags": [
     "Templates"
    ],
    "summary": "Create Category",
    "requestType": "http",
    "operationId": "create_createTemplateCategory",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}/relationships/files#updateTemplateCategory": {
   "post": {
    "tags": [
     "Templates"
    ],
    "summary": "Update Template Category",
    "requestType": "http",
    "operationId": "addRelations_updateTemplateCategory",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections#createExternalCollection": {
   "post": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Create External Collection",
    "requestType": "http",
    "operationId": "create_createExternalCollection",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections#createInternalCollection": {
   "post": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Create Internal Collection",
    "requestType": "http",
    "operationId": "create_createInternalCollection",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/comments#addReply": {
   "post": {
    "tags": [
     "Comments"
    ],
    "summary": "Create Reply",
    "requestType": "http",
    "operationId": "create_addReply",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/comments#addComment": {
   "post": {
    "tags": [
     "Comments"
    ],
    "summary": "Create Comment",
    "requestType": "http",
    "operationId": "create_addComment",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}/customfields#createCustomField": {
   "post": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Create Custom Field",
    "requestType": "http",
    "operationId": "create_createCustomField",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/custommetadata#associateFileFolderToDataTemplate": {
   "post": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Associate File/Folder to Data Template",
    "requestType": "http",
    "operationId": "create_associateFileFolderToDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/custommetadata#associateMultipleFileFolderToDataTemplate": {
   "post": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Associate Multiple Files/Folders to Data Template",
    "requestType": "http",
    "bulkLimit": "100",
    "operationId": "create_associateMultipleFileFolderToDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/datatemplates#createDataTemplate": {
   "post": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Create Data Template",
    "requestType": "http",
    "operationId": "create_createDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}/dlppolicy#createDlpPolicy": {
   "post": {
    "tags": [
     "DLP Policy"
    ],
    "summary": "Create a Data Loss Prevention Policy",
    "requestType": "http",
    "operationId": "create_createDlpPolicy",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DlpPolicy.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/groupmembers#addMemberInGroup": {
   "post": {
    "tags": [
     "Group Members"
    ],
    "summary": "Add Multiple Members to Group",
    "requestType": "http",
    "bulkLimit": "50",
    "operationId": "create_addMemberInGroup",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/groups#createGroup": {
   "post": {
    "tags": [
     "Groups"
    ],
    "summary": "Create Group",
    "requestType": "http",
    "operationId": "create_createGroup",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/labels#createLabel": {
   "post": {
    "tags": [
     "Labels"
    ],
    "summary": "Create Label",
    "requestType": "http",
    "operationId": "create_createLabel",
    "security": [
     {
      "Authorization": [
       "WorkDrive.labels.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}/relationships/files#addResourceLabels": {
   "post": {
    "tags": [
     "Labels"
    ],
    "summary": "Add Label to File/Folder",
    "requestType": "http",
    "operationId": "addRelations_addResourceLabels",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/links#createShareLink": {
   "post": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Create External Share Custom Link",
    "requestType": "http",
    "operationId": "create_createShareLink",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/links#createDownloadLink": {
   "post": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Create External Share Download Link",
    "requestType": "http",
    "operationId": "create_createDownloadLink",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/members#shareTeamFolder": {
   "post": {
    "tags": [
     "Team Folder Members"
    ],
    "summary": "Add Members To Team Folder",
    "requestType": "http",
    "operationId": "create_shareTeamFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/members#shareGroupsTeamFolder": {
   "post": {
    "tags": [
     "Team Folder Members"
    ],
    "summary": "Add Groups to Team Folder",
    "requestType": "http",
    "operationId": "create_shareGroupsTeamFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions#shareGroupMember": {
   "post": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Share Files/Folders to Group Members",
    "requestType": "http",
    "operationId": "create_shareGroupMember",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions#shareEveryOne": {
   "post": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Share Files/Folders to everyone on the Internet",
    "requestType": "http",
    "operationId": "create_shareEveryOne",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions#generateEmbed": {
   "post": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Generate Embed Code for a Files/Folders",
    "requestType": "http",
    "operationId": "create_generateEmbed",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions#shareIndividual": {
   "post": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Share Files/Folders to Individual Team Members",
    "requestType": "http",
    "operationId": "create_shareIndividual",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions#shareTeam": {
   "post": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Share Files/Folders with Team",
    "requestType": "http",
    "operationId": "create_shareTeam",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/importfile#importToNative": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Convert File to Zoho Format",
    "requestType": "http",
    "operationId": "create_importToNative",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/copy#multipleCopy": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Copy Multiple Files/Folders",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "create_multipleCopy",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/linkfile#createLinkFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Create Link file",
    "requestType": "http",
    "operationId": "create_createLinkFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#createCustomizedFolder": {
   "post": {
    "tags": [
     "Folder Customization"
    ],
    "summary": "Create a new Customized Folder",
    "requestType": "http",
    "operationId": "create_createCustomizedFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{library_id}/saveastemplate#saveresourceastemplate": {
   "post": {
    "tags": [
     "Templates"
    ],
    "summary": "Save File as Template",
    "requestType": "array",
    "operationId": "create_saveresourceastemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#createFolder": {
   "post": {
    "tags": [
     "Folders"
    ],
    "summary": "Create Folder",
    "requestType": "http",
    "operationId": "create_createFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#createNewFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Create Zoho format files",
    "requestType": "http",
    "operationId": "create_createNewFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/copy#copyResource": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Copy File/Folder",
    "requestType": "http",
    "operationId": "create_copyResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders#CreateTeamFolder": {
   "post": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Create Team Folder",
    "requestType": "http",
    "operationId": "create_CreateTeamFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}/unzip#unZipFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Unzip File",
    "requestType": "http",
    "operationId": "create_unZipFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "api/v1/users#InviteNewUsers": {
   "post": {
    "tags": [
     "Team Members"
    ],
    "summary": "Invite New Member to Team",
    "requestType": "http",
    "bulkLimit": "500",
    "operationId": "create_InviteNewUsers",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/versions#restoreToVersion": {
   "post": {
    "tags": [
     "File Version"
    ],
    "summary": "Restore as Top Version",
    "requestType": "http",
    "operationId": "create_restoreToVersion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/createzip#createZipFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Create Multiple Files/Folders as ZIP",
    "requestType": "http",
    "operationId": "doPost_createZipFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.READ"
      ]
     }
    ]
   }
  },
  "workdrive-api/v1/stream/upload#chunkFileUpload": {
   "post": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Large File Upload as Chunks",
    "requestType": "http",
    "operationId": "doPost_chunkFileUpload",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE,ZohoFiles.files.CREATE"
      ]
     }
    ],
    "servers": [
     {
      "url": "https://upload.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "api/v1/upload#UploadFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Upload File",
    "requestType": "http",
    "operationId": "doPost_UploadFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/upload#UploadNewVersion": {
   "post": {
    "tags": [
     "File Version"
    ],
    "summary": "Upload New Version",
    "requestType": "http",
    "operationId": "doPost_UploadNewVersion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "workdrive-api/v1/stream/upload#UploadLargeFile": {
   "post": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Upload Large File >250MB",
    "requestType": "http",
    "operationId": "doPut_UploadLargeFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE,ZohoFiles.files.CREATE"
      ]
     }
    ],
    "servers": [
     {
      "url": "https://upload.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "api/v1/uploadsession/{resource_id}/commit#chunkRevisionUploadCommitSession": {
   "post": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Commit Session for Revision Upload",
    "requestType": "http",
    "operationId": "doPost_chunkRevisionUploadCommitSession",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/uploadsession/create#chunkUploadCreateSession": {
   "post": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Create Session (Normal Upload)",
    "requestType": "http",
    "operationId": "doPost_chunkUploadCreateSession",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/uploadsession/commit#chunkUploadCommitSession": {
   "post": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Commit Session (Normal Upload)",
    "requestType": "http",
    "operationId": "doPost_chunkUploadCommitSession",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/uploadsession/{resource_id}/create#chunkRevisionUploadCreateSession": {
   "post": {
    "tags": [
     "Chunk Upload"
    ],
    "summary": "Create Session for Revision Upload",
    "requestType": "http",
    "operationId": "doPost_chunkRevisionUploadCreateSession",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}#deleteTemplateCategory": {
   "patch": {
    "tags": [
     "Templates"
    ],
    "summary": "Delete Category",
    "requestType": "http",
    "operationId": "save_deleteTemplateCategory",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}#renameTemplateCategory": {
   "patch": {
    "tags": [
     "Templates"
    ],
    "summary": "Rename Category",
    "requestType": "http",
    "operationId": "save_renameTemplateCategory",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#externalToInternal": {
   "patch": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Convert External Collection into Internal Collection",
    "requestType": "http",
    "operationId": "save_externalToInternal",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#internalToExternal": {
   "patch": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Convert Internal Collection into External Collection",
    "requestType": "http",
    "operationId": "save_internalToExternal",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#updateCollectionSettings": {
   "patch": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Update Collection Link Settings",
    "requestType": "http",
    "operationId": "save_updateCollectionSettings",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#disable": {
   "patch": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Disable Collection",
    "requestType": "http",
    "operationId": "save_disable",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#enable": {
   "patch": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Enable Collection",
    "requestType": "http",
    "operationId": "save_enable",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/comments/{comment_id}#editComment": {
   "patch": {
    "tags": [
     "Comments"
    ],
    "summary": "Edit Comment",
    "requestType": "http",
    "operationId": "save_editComment",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/comments/{comment_id}#resolveComment": {
   "patch": {
    "tags": [
     "Comments"
    ],
    "summary": "Resolve Comment",
    "requestType": "http",
    "operationId": "save_resolveComment",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/comments/{comment_id}#reopenComment": {
   "patch": {
    "tags": [
     "Comments"
    ],
    "summary": "Reopen Comment",
    "requestType": "http",
    "operationId": "save_reopenComment",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/customfields/{custom_field_id}#updateCustomField": {
   "patch": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Update Custom Field",
    "requestType": "http",
    "operationId": "save_updateCustomField",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/custommetadata/{custommetadata_id}#updateValuesOfAssociatedFilesFolders": {
   "patch": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Update Values of Associated Files/Folders",
    "requestType": "http",
    "operationId": "save_updateValuesOfAssociatedFilesFolders",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}#changeDataTemplateDescription": {
   "patch": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Change Data Template Description",
    "requestType": "http",
    "operationId": "save_changeDataTemplateDescription",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}#renameDataTemplate": {
   "patch": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Rename Data Template",
    "requestType": "http",
    "operationId": "save_renameDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}#enableDisableDataTemplate": {
   "patch": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Enable/Disable Data Template",
    "requestType": "http",
    "operationId": "save_enableDisableDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/dlpPolicy/{dlp_policy_id}#renameDlpPolicy": {
   "patch": {
    "tags": [
     "DLP Policy"
    ],
    "summary": "Rename Data Loss Prevention Policy",
    "requestType": "http",
    "operationId": "save_renameDlpPolicy",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DlpPolicy.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/dlpPolicy/{dlp_policy_id}#changeDlpPolicyDescription": {
   "patch": {
    "tags": [
     "DLP Policy"
    ],
    "summary": "Change Data Template Description",
    "requestType": "http",
    "operationId": "save_changeDlpPolicyDescription",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DlpPolicy.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/dlpPolicy/{dlp_policy_id}#enableDisableDlpPolicy": {
   "patch": {
    "tags": [
     "DLP Policy"
    ],
    "summary": "Enable/Disable Data Loss Prevention Policy",
    "requestType": "http",
    "operationId": "save_enableDisableDlpPolicy",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DlpPolicy.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/groupmembers/{group_member_id}#updateMemberRole": {
   "patch": {
    "tags": [
     "Group Members"
    ],
    "summary": "Update Group Member Role",
    "requestType": "http",
    "operationId": "save_updateMemberRole",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/groups/{group_id}#renameGroup": {
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Rename Group",
    "requestType": "http",
    "operationId": "save_renameGroup",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/groups/{group_id}#updateGroupDescription": {
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update Group Description",
    "requestType": "http",
    "operationId": "save_updateGroupDescription",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}#changeLabelColor": {
   "patch": {
    "tags": [
     "Labels"
    ],
    "summary": "Change Label Color",
    "requestType": "http",
    "operationId": "save_changeLabelColor",
    "security": [
     {
      "Authorization": [
       "WorkDrive.labels.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}#renameLabel": {
   "patch": {
    "tags": [
     "Labels"
    ],
    "summary": "Rename Label",
    "requestType": "http",
    "operationId": "save_renameLabel",
    "security": [
     {
      "Authorization": [
       "WorkDrive.labels.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/libraries/{library_id}#updateLibraryUserViewPreference": {
   "patch": {
    "tags": [
     "Templates"
    ],
    "summary": "Change Sort Type and Order",
    "requestType": "http",
    "operationId": "save_updateLibraryUserViewPreference",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/links/{link_id}#updateLinkDownloadSetting": {
   "patch": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Change Download Link Settings",
    "requestType": "http",
    "operationId": "save_updateLinkDownloadSetting",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/links/{link_id}#updateLinkPasswordSetting": {
   "patch": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Change Password Link Settings",
    "requestType": "http",
    "operationId": "save_updateLinkPasswordSetting",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/links/{link_id}#updateLinkExpirySetting": {
   "patch": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Change Expiration Settings",
    "requestType": "http",
    "operationId": "save_updateLinkExpirySetting",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/members/{member_id}#updateTeamFolderMember": {
   "patch": {
    "tags": [
     "Team Folder Members"
    ],
    "summary": "Update Member Role in Team Folder",
    "requestType": "http",
    "operationId": "save_updateTeamFolderMember",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions/{permission_id}#updateExpiration": {
   "patch": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Update File/Folder Share Expiration",
    "requestType": "http",
    "operationId": "save_updateExpiration",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions/{permission_id}#updatePermission": {
   "patch": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Update File/Folder Share Permissions",
    "requestType": "http",
    "operationId": "save_updatePermission",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#removeFileFavorite": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Remove File/Folder from Favorites",
    "requestType": "http",
    "operationId": "save_removeFileFavorite",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#restoreResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Restore File/Folder",
    "requestType": "http",
    "operationId": "save_restoreResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#multipleRestore": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Restore Multiple Files/Folders",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_multipleRestore",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#multipleDelete": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Permanent Delete Multiple Files/Folders",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_multipleDelete",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#multipleTrash": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Move Multiple Files/Folders to Trash",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_multipleTrash",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#removeFinal": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Enable Editing for File",
    "requestType": "http",
    "operationId": "save_removeFinal",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#addFolderCustomization": {
   "patch": {
    "tags": [
     "Folder Customization"
    ],
    "summary": "Customize an existing folder",
    "requestType": "http",
    "operationId": "save_addFolderCustomization",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#checkoutResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Check out File",
    "requestType": "http",
    "operationId": "save_checkoutResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#renameResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Rename File/Folder",
    "requestType": "http",
    "operationId": "save_renameResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#moveResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Move File/Folder",
    "requestType": "http",
    "operationId": "save_moveResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#deleteResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Permanent Delete File/Folder",
    "requestType": "http",
    "operationId": "save_deleteResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#markAsReady": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Mark File as Ready",
    "requestType": "http",
    "operationId": "save_markAsReady",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#trashResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Move File/Folder to Trash",
    "requestType": "http",
    "operationId": "save_trashResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#removeFavoriteMultiple": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Remove Multiple Files/Folders from Favorites",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_removeFavoriteMultiple",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#followResource": {
   "patch": {
    "tags": [
     "Follow Updates"
    ],
    "summary": "Follow File/Folder",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_followResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#markFinal": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Mark File as Final",
    "requestType": "http",
    "operationId": "save_markFinal",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#markFavoriteMultiple": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Mark Multiple Files/Folders as Favorites",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_markFavoriteMultiple",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#multipleMove": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Move Multiple Files/Folders",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_multipleMove",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#updateLinkFile": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Update Link file",
    "requestType": "http",
    "operationId": "save_updateLinkFile",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#removeFolderCustomization": {
   "patch": {
    "tags": [
     "Folder Customization"
    ],
    "summary": "Remove Folder Customization",
    "requestType": "http",
    "operationId": "save_removeFolderCustomization",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#markFileFavorite": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Mark File/Folder as Favorites",
    "requestType": "http",
    "operationId": "save_markFileFavorite",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files/{resource_id}#unlockResource": {
   "patch": {
    "tags": [
     "Files/Folders"
    ],
    "summary": "Check in File",
    "requestType": "http",
    "operationId": "save_unlockResource",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/files#unfollow": {
   "patch": {
    "tags": [
     "Follow Updates"
    ],
    "summary": "Unfollow File/Folder",
    "requestType": "http",
    "bulkLimit": "200",
    "operationId": "save_unfollow",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/settings/{teamfolder_id}#allowExternalShare": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Enable External Sharing",
    "requestType": "http",
    "operationId": "save_allowExternalShare",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/settings/{myfolder_id}#allowUserDocumentConversion": {
   "patch": {
    "tags": [
     "My Folders Files"
    ],
    "summary": "Enable File Conversion",
    "requestType": "http",
    "operationId": "save_allowUserDocumentConversion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/settings/{teamfolder_id}#allowDocumentConversion": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Enable File Conversion",
    "requestType": "http",
    "operationId": "save_allowDocumentConversion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/settings/{teamfolder_id}#allowViewerDownload": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Allow Viewer to Download",
    "requestType": "http",
    "operationId": "save_allowViewerDownload",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#Unpin-TeamFolder": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Unpin Team Folder",
    "requestType": "http",
    "operationId": "save_Unpin-TeamFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#pinTeamFolder": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Pin Team Folder",
    "requestType": "http",
    "operationId": "save_pinTeamFolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#updateTeamFolderDesc": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Change Team Folder Description",
    "requestType": "http",
    "operationId": "save_updateTeamFolderDesc",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#updateTeamFolderName": {
   "patch": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Change Team Folder Name",
    "requestType": "http",
    "operationId": "save_updateTeamFolderName",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}#renameTeam": {
   "patch": {
    "tags": [
     "Teams"
    ],
    "summary": "Change Team Name",
    "requestType": "http",
    "operationId": "save_renameTeam",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}#changePreferedTeam": {
   "patch": {
    "tags": [
     "Teams"
    ],
    "summary": "Change Preferred Team",
    "requestType": "http",
    "operationId": "save_changePreferedTeam",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/teams/{team_id}#updateDescription": {
   "patch": {
    "tags": [
     "Teams"
    ],
    "summary": "Change Team Description",
    "requestType": "http",
    "operationId": "save_updateDescription",
    "security": [
     {
      "Authorization": [
       "WorkDrive.team.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}#updateUserRole": {
   "patch": {
    "tags": [
     "Team Members"
    ],
    "summary": "Change Team Member's role",
    "requestType": "http",
    "operationId": "save_updateUserRole",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}#suspendUser": {
   "patch": {
    "tags": [
     "Team Members"
    ],
    "summary": "Suspend Team Member",
    "requestType": "http",
    "operationId": "save_suspendUser",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}#deleteUser": {
   "patch": {
    "tags": [
     "Team Members"
    ],
    "summary": "Delete Team Member",
    "requestType": "http",
    "operationId": "save_deleteUser",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/users/{team_member_id}#updateOrgTemplateAdminRole": {
   "patch": {
    "tags": [
     "Templates"
    ],
    "summary": "Assign/Remove Template Admin role",
    "requestType": "http",
    "operationId": "save_updateOrgTemplateAdminRole",
    "security": [
     {
      "Authorization": [
       "WorkDrive.users.UPDATE"
      ]
     }
    ]
   }
  },
  "api/v1/category/{category_id}/relationships/files#removeTemplateCategory": {
   "delete": {
    "tags": [
     "Templates"
    ],
    "summary": "Remove Template Category",
    "requestType": "http",
    "operationId": "removeRelations_removeTemplateCategory",
    "security": [
     {
      "Authorization": [
       "WorkDrive.libraries.categories.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/collections/{collection_id}#DeleteCollection": {
   "delete": {
    "tags": [
     "Collect Files"
    ],
    "summary": "Delete Collection",
    "requestType": "http",
    "operationId": "delete_DeleteCollection",
    "security": [
     {
      "Authorization": [
       "WorkDrive.Collection.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/comments/{comment_id}#deleteComment": {
   "delete": {
    "tags": [
     "Comments"
    ],
    "summary": "Delete Comment",
    "requestType": "http",
    "operationId": "delete_deleteComment",
    "security": [
     {
      "Authorization": [
       "WorkDrive.comments.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/customfields/{custom_field_id}#deleteCustomField": {
   "delete": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Delete Custom Field",
    "requestType": "http",
    "operationId": "delete_deleteCustomField",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/custommetadata/{custommetadata_id}#disassociateFilesFoldersFromDataTemplate": {
   "delete": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Disassociate Files/Folders from Data Template",
    "requestType": "http",
    "operationId": "delete_disassociateFilesFoldersFromDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/datatemplates/{data_template_id}#deleteDataTemplate": {
   "delete": {
    "tags": [
     "Data Templates and Custom Fields"
    ],
    "summary": "Delete Data Template",
    "requestType": "http",
    "operationId": "delete_deleteDataTemplate",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DataTemplates.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/dlppolicy/{dlpPolicyId}#deleteDlpPolicy": {
   "delete": {
    "tags": [
     "DLP Policy"
    ],
    "summary": "Delete Data Loss Prevention Policy",
    "requestType": "http",
    "operationId": "delete_deleteDlpPolicy",
    "security": [
     {
      "Authorization": [
       "WorkDrive.DlpPolicy.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/groupmembers/{group_member_id}#deleteMember": {
   "delete": {
    "tags": [
     "Group Members"
    ],
    "summary": "Remove Group Member",
    "requestType": "http",
    "operationId": "delete_deleteMember",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/groups/{group_id}#deleteGroup": {
   "delete": {
    "tags": [
     "Groups"
    ],
    "summary": "Delete Group",
    "requestType": "http",
    "operationId": "delete_deleteGroup",
    "security": [
     {
      "Authorization": [
       "WorkDrive.groups.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}#deleteLabel": {
   "delete": {
    "tags": [
     "Labels"
    ],
    "summary": "Delete Label",
    "requestType": "http",
    "operationId": "delete_deleteLabel",
    "security": [
     {
      "Authorization": [
       "WorkDrive.labels.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/labels/{label_id}/relationships/files#removeResourceLabels": {
   "delete": {
    "tags": [
     "Labels"
    ],
    "summary": "Remove Label from File/Folder",
    "requestType": "http",
    "operationId": "removeRelations_removeResourceLabels",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.CREATE"
      ]
     }
    ]
   }
  },
  "api/v1/links/{link_id}#deleteSharedLink": {
   "delete": {
    "tags": [
     "External Sharing"
    ],
    "summary": "Revoke External Share Link",
    "requestType": "http",
    "operationId": "delete_deleteSharedLink",
    "security": [
     {
      "Authorization": [
       "WorkDrive.links.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/members/{member_id}#deleteMember": {
   "delete": {
    "tags": [
     "Team Folder Sharing"
    ],
    "summary": "Delete TeamFolder Share Access",
    "requestType": "http",
    "operationId": "delete_deleteMember",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/members/{member_id}#deleteTeamFolderMember": {
   "delete": {
    "tags": [
     "Team Folder Members"
    ],
    "summary": "Delete Member from Team Folder",
    "requestType": "http",
    "operationId": "delete_deleteTeamFolderMember",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.sharing.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/permissions/{permission_id}#deletePermission": {
   "delete": {
    "tags": [
     "File/Folder Sharing"
    ],
    "summary": "Delete File/Folder Share Access",
    "requestType": "http",
    "operationId": "delete_deletePermission",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.sharing.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/teamfolders/{teamfolder_id}#deleteTeamfolder": {
   "delete": {
    "tags": [
     "Team Folder"
    ],
    "summary": "Delete Team Folder",
    "requestType": "http",
    "operationId": "delete_deleteTeamfolder",
    "security": [
     {
      "Authorization": [
       "WorkDrive.teamfolders.DELETE"
      ]
     }
    ]
   }
  },
  "api/v1/versions/{version_id}#deleteVersion": {
   "delete": {
    "tags": [
     "File Version"
    ],
    "summary": "Delete Version",
    "requestType": "http",
    "operationId": "delete_deleteVersion",
    "security": [
     {
      "Authorization": [
       "WorkDrive.files.DELETE"
      ]
     }
    ]
   }
  },
  "/http-request-methods": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "HTTP Request Methods",
    "operationId": "http-request-methods"
   }
  },
  "/http-status-code": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Http Status Code",
    "operationId": "http-status-code"
   }
  },
  "/request-response-structure": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Request and Response Structure",
    "operationId": "request-response-structure"
   }
  },
  "/encode-query-parameter": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Encode Query Parameter",
    "operationId": "encode-query-parameter"
   }
  },
  "/request-header": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Request Header",
    "operationId": "request-header"
   }
  },
  "/pagination": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Pagination",
    "operationId": "pagination"
   }
  },
  "/multi-dc-support": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Multi DC Support",
    "operationId": "multi-dc-support"
   }
  },
  "/filters": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Filters",
    "operationId": "filters"
   }
  },
  "/fetching-ids": {
   "text": {
    "tags": [
     "getting started"
    ],
    "summary": "Fetching IDs",
    "operationId": "fetching-ids"
   }
  },
  "/scopes": {
   "text": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Scopes",
    "operationId": "scopes"
   }
  },
  "/register-application": {
   "text": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Register your application",
    "operationId": "register-application"
   }
  },
  "oauth/v2/auth#authorizationRequest": {
   "get": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Authorization Request",
    "operationId": "authorization-request",
    "servers": [
     {
      "url": "https://accounts.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "oauth/v2/token#accessRefreshToken": {
   "post": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Generate Access And Refresh Token",
    "operationId": "access-refresh-token",
    "servers": [
     {
      "url": "https://accounts.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "oauth/v2/token#regenerateAccessToken": {
   "post": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Regenerate Access Token",
    "operationId": "regenerate-access-token",
    "servers": [
     {
      "url": "https://accounts.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "oauth/v2/token#revokeRefreshToken": {
   "post": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Revoke Refresh Token",
    "operationId": "revoke-refresh-token",
    "servers": [
     {
      "url": "https://accounts.zoho.com",
      "variables": {}
     }
    ]
   }
  },
  "/token-validity": {
   "text": {
    "tags": [
     "OAuth 2.0 Authentication"
    ],
    "summary": "Token Validity",
    "operationId": "token-validity"
   }
  }
 },
 "components": {
 }
}